"""添加数据库索引

Revision ID: 13cec903f589
Revises: de778012c337
Create Date: 2026-03-18 11:45:21.154863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cec903f589'
down_revision = 'de778012c337'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### 添加数据库索引 ###
    # 获取数据库连接
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 获取现有索引
    existing_indexes = inspector.get_indexes('audio_source')
    audio_index_names = [idx['name'] for idx in existing_indexes]

    # 为 audio_source 添加索引
    with op.batch_alter_table('audio_source', schema=None) as batch_op:
        if 'idx_create_time' not in audio_index_names:
            batch_op.create_index('idx_create_time', ['create_time'], unique=False)
        if 'idx_del_flag' not in audio_index_names:
            batch_op.create_index('idx_del_flag', ['del_flag'], unique=False)

    # 获取 video_source 现有索引
    existing_indexes = inspector.get_indexes('video_source')
    video_index_names = [idx['name'] for idx in existing_indexes]

    # 为 video_source 添加索引
    with op.batch_alter_table('video_source', schema=None) as batch_op:
        if 'idx_create_time' not in video_index_names:
            batch_op.create_index('idx_create_time', ['create_time'], unique=False)
        if 'idx_del_flag' not in video_index_names:
            batch_op.create_index('idx_del_flag', ['del_flag'], unique=False)
        if 'idx_video_type' not in video_index_names:
            batch_op.create_index('idx_video_type', ['video_type'], unique=False)
        if 'idx_video_type_del_flag' not in video_index_names:
            batch_op.create_index('idx_video_type_del_flag', ['video_type', 'del_flag'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_source', schema=None) as batch_op:
        batch_op.drop_index('idx_video_type_del_flag')
        batch_op.drop_index('idx_video_type')
        batch_op.drop_index('idx_del_flag')
        batch_op.drop_index('idx_create_time')

    with op.batch_alter_table('audio_source', schema=None) as batch_op:
        batch_op.drop_index('idx_del_flag')
        batch_op.drop_index('idx_create_time')

    # ### end Alembic commands ###
