"""add_output_videos_to_video_project

Revision ID: 1d44fe6a55ac
Revises: 91dab1eac231
Create Date: 2026-04-12 00:09:02.983098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d44fe6a55ac'
down_revision = '91dab1eac231'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_videos', sa.JSON(), nullable=True, comment='输出视频列表 [{path, created_at}]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_projects', schema=None) as batch_op:
        batch_op.drop_column('output_videos')

    # ### end Alembic commands ###
