"""add project_temp_file table

Revision ID: 48f3f18dbeb2
Revises: 7bbe3f8c2941
Create Date: 2026-04-28 22:40:10.662740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f3f18dbeb2'
down_revision = '7bbe3f8c2941'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_temp_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('web_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_temp_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_temp_file_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_temp_file_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_temp_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_temp_file_session_id'))
        batch_op.drop_index(batch_op.f('ix_project_temp_file_project_id'))

    op.drop_table('project_temp_file')
    # ### end Alembic commands ###
