"""添加 video_projects 表

Revision ID: 5df6e1d28b37
Revises: 44bdba402746
Create Date: 2026-04-05 15:04:12.487648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df6e1d28b37'
down_revision = '44bdba402746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip_plan_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目 ID'),
    sa.Column('sequence', sa.Integer(), nullable=True, comment='顺序'),
    sa.Column('material_id', sa.Integer(), nullable=True, comment='素材 ID'),
    sa.Column('material_name', sa.String(length=255), nullable=True, comment='素材名称'),
    sa.Column('start_time', sa.String(length=20), nullable=True, comment='素材开始时间'),
    sa.Column('end_time', sa.String(length=20), nullable=True, comment='素材结束时间'),
    sa.Column('duration', sa.Float(), nullable=True, comment='片段时长'),
    sa.Column('purpose', sa.Text(), nullable=True, comment='用途说明'),
    sa.Column('transition_type', sa.String(length=50), nullable=True, comment='转场类型'),
    sa.Column('transition_duration', sa.Float(), nullable=True, comment='转场时长'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='状态: draft/processing/completed'),
    sa.Column('duration', sa.Float(), nullable=True, comment='总时长（秒）'),
    sa.Column('timeline_data', sa.JSON(), nullable=True, comment='时间线数据（JSON）'),
    sa.Column('plan_data', sa.JSON(), nullable=True, comment='剪辑方案数据（JSON）'),
    sa.Column('output_path', sa.String(length=500), nullable=True, comment='输出文件路径'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_projects')
    op.drop_table('clip_plan_items')
    # ### end Alembic commands ###
