"""初始化数据库结构

Revision ID: 6d2b87fb0031
Revises: 
Create Date: 2026-03-27 17:23:02.923771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2b87fb0031'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audio_name'))
        batch_op.drop_index(batch_op.f('idx_create_time'))
        batch_op.drop_index(batch_op.f('idx_del_flag'))
        batch_op.drop_index(batch_op.f('idx_seed'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_seed'), ['seed'], unique=False)
        batch_op.create_index(batch_op.f('idx_del_flag'), ['del_flag'], unique=False)
        batch_op.create_index(batch_op.f('idx_create_time'), ['create_time'], unique=False)
        batch_op.create_index(batch_op.f('idx_audio_name'), ['audio_name'], unique=False)

    # ### end Alembic commands ###
