"""add_project_centric_fields

Revision ID: 728e73f283ff
Revises: cfdf805be0bb
Create Date: 2026-04-06 00:04:19.027220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728e73f283ff'
down_revision = 'cfdf805be0bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True, comment='模式: workflow/conversation'))
        batch_op.add_column(sa.Column('material_ids', sa.JSON(), nullable=True, comment='素材ID列表'))
        batch_op.add_column(sa.Column('creative', sa.Text(), nullable=True, comment='文案内容'))
        batch_op.add_column(sa.Column('target_duration', sa.Float(), nullable=True, comment='目标时长（秒）'))
        batch_op.add_column(sa.Column('style', sa.String(length=50), nullable=True, comment='风格'))
        batch_op.add_column(sa.Column('speaker_id', sa.Integer(), nullable=True, comment='音色ID'))
        batch_op.add_column(sa.Column('tts_path', sa.String(length=500), nullable=True, comment='TTS音频路径'))
        batch_op.add_column(sa.Column('bgm_id', sa.Integer(), nullable=True, comment='BGM ID'))
        batch_op.add_column(sa.Column('bgm_volume', sa.Float(), nullable=True, comment='BGM音量'))
        batch_op.add_column(sa.Column('current_step', sa.Integer(), nullable=True, comment='当前步骤(0-3)'))
        batch_op.add_column(sa.Column('chat_history', sa.JSON(), nullable=True, comment='对话历史'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_projects', schema=None) as batch_op:
        batch_op.drop_column('chat_history')
        batch_op.drop_column('current_step')
        batch_op.drop_column('bgm_volume')
        batch_op.drop_column('bgm_id')
        batch_op.drop_column('tts_path')
        batch_op.drop_column('speaker_id')
        batch_op.drop_column('style')
        batch_op.drop_column('target_duration')
        batch_op.drop_column('creative')
        batch_op.drop_column('material_ids')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
