"""add dialog_sessions table

Revision ID: 91dab1eac231
Revises: 728e73f283ff
Create Date: 2026-04-11 14:48:01.506639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91dab1eac231'
down_revision = '728e73f283ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 UUID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: idle/collecting/confirming/executing/completed/error'),
    sa.Column('intent', sa.String(length=50), nullable=True, comment='当前意图'),
    sa.Column('slots', sa.JSON(), nullable=True, comment='槽位数据'),
    sa.Column('history', sa.JSON(), nullable=True, comment='对话历史'),
    sa.Column('current_video_id', sa.Integer(), nullable=True, comment='当前视频 ID'),
    sa.Column('pending_action', sa.JSON(), nullable=True, comment='待执行操作'),
    sa.Column('plan', sa.JSON(), nullable=True, comment='剪辑方案'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='扩展元数据'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dialog_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dialog_sessions_session_id'), ['session_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialog_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dialog_sessions_session_id'))

    op.drop_table('dialog_sessions')
    # ### end Alembic commands ###
