"""添加 bgm_library 表

Revision ID: cfdf805be0bb
Revises: 5df6e1d28b37
Create Date: 2026-04-05 18:41:03.847658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdf805be0bb'
down_revision = '5df6e1d28b37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bgm_library',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='BGM名称'),
    sa.Column('web_path', sa.Text(), nullable=True, comment='Web访问路径'),
    sa.Column('local_path', sa.Text(), nullable=True, comment='本地存储路径'),
    sa.Column('style', sa.String(length=100), nullable=True, comment='风格标签'),
    sa.Column('duration', sa.Float(), nullable=True, comment='时长(秒)'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bgm_library')
    # ### end Alembic commands ###
