"""初始化数据库表结构

Revision ID: de778012c337
Revises: 
Create Date: 2026-01-06 15:02:20.676700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de778012c337'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('audio_name', sa.Text(), nullable=True, comment='音频名称'),
    sa.Column('prompt_text', sa.Text(), nullable=True, comment='参考文本'),
    sa.Column('web_path', sa.Text(), nullable=True, comment='Web访问路径'),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('del_flag', sa.SmallInteger(), nullable=True, comment='逻辑删除 0:未删除 1:已删除'),
    sa.Column('seed', sa.Integer(), nullable=True, comment='随机种子参数[1-100000]'),
    sa.Column('speed', sa.Float(), nullable=True, comment='速度因子'),
    sa.Column('top_p', sa.Float(), nullable=True, comment='top_p采样参数'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='温度参数'),
    sa.Column('repetition_penalty', sa.Float(), nullable=True, comment='重复惩罚因子'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('video_name', sa.Text(), nullable=True, comment='视频名称'),
    sa.Column('web_path', sa.Text(), nullable=True, comment='Web访问路径'),
    sa.Column('local_path', sa.Text(), nullable=True, comment='本地存储路径'),
    sa.Column('duration', sa.Text(), nullable=True, comment='视频时长（秒）'),
    sa.Column('duration_hms', sa.Text(), nullable=True, comment='视频时长（HH:MM:SS）'),
    sa.Column('description', sa.Text(), nullable=True, comment='视频描述'),
    sa.Column('video_type', sa.SmallInteger(), nullable=True, comment='视频类型 0:未使用 1:使用中'),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('del_flag', sa.SmallInteger(), nullable=True, comment='逻辑删除 0:未删除 1:已删除'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_source')
    op.drop_table('audio_source')
    # ### end Alembic commands ###
